language: node_js
install: nvm install v8.1.3
node_js:
   - “8.1.3”
cache:
  directories:
    - node_modules
before_deploy: yarn build
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_DEPLOY_TOKEN